name: innoprod
channels:
 - defaults
 - conda-forge
dependencies:
 - conda=26.1.0
 - google-api-python-client=2.189.0
 - google-auth=2.48.0
 - google-auth-oauthlib=1.2.2
 - jupyter=1.1.1
 - matplotlib=3.10.8
 - nltk=3.9.2
 - pandas=3.0.0
 - pip=25.1
 - python=3.13.5
 - python-dotenv=1.1.0
 - requests=2.32.4
 - scikit-learn=1.8.0
 - statsmodels=0.14.6
